services:
  - type: web
    name: todo-server
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://dbuser:dbpass123@cluster0.sn8whdg.mongodb.net/todo_db
      - key: CLIENT_URL
        value: "*"
