services:
  - type: web
    name: mern-products-api
    env: node
    rootDir: server
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://dbuser:dbpass123@cluster0.sn8whdg.mongodb.net/products_db
      - key: PORT
        value: 5000
